### ISSUE TITLE
updating fields to an empty value results in a 507 error

### ISSUE THREAD

**Issue by gractrit** [24u/fmRESTor#4]
When setting a field to an empty value using editRecord, I get the error response code 507 with the message, "Value in field failed calculation test of validation entry option".

The scenario is that I'm updating a bunch of fields in a record.  Some of the fields have a value, and I'm looking set them to empty.

fieldData array looks something like this:
Array
(
    [field_1] => 5
    [field_2] => banana
    [field_3] => 
)

field_3 index is empty and should make the field in FileMaker empty.

Even if there are no validation restrictions on the field in FileMaker, I still get the 507 error.

**Comment by mbcbus** [comment]
@gractrit - Error 507 is coming back from FileMaker, not from fmRESTor, so something about the data you are sending to FileMaker is causing an issue.

In PHP (and in JSON for reference), empty is a different thing than null. Do you know if you're passing an empty or a null value in?

**Comment by gractrit** [comment]
@mbcbus from my testing, I get a 507 error from FileMaker when using fmRESTor whether I send a value that is an empty string or null.  

My question another way... How do I delete the contents of a field in FileMaker using fmRESTor?  I have yet to find the correct technique.

When I send a raw PATCH HTTP request directly to the FileMaker API (eg. with insomnia or postman), I format the JSON value for the field with empty quotes:
{ 
  "fieldData": 
    {
      "field_1": "",
      "field_2": "",
      "field_3": ""
    }
}

That works fine.  After the call, the fields are empty (no value).  

With fmRESTor, if I create an array element with an empty string, or set to null or false, I get the 507 error.

**Update:** Upon further testing I found the value being passed to fmRESTor was in fact NOT an empty value, but was still null.  I added another check with === null and if that is true, I set the value to empty string "".  With that in place, fmRESTor works.

Since FileMaker doesn't seem to accept null as an empty value, would it make sense for fmRESTor to convert nulls to empty strings before json encoding?

**Comment by mbcbus** [comment]
@gractrit - I think it may be a type-conversion issue then. I've seen error 507 passed back as an error when I've tried to send an array() into it without converting to string first. 

When this happened I used the implode() function to collapse my array into a delimited list (EG: Item 1|||Item 2|||Item 3), and then ran a post-action script on filemaker to parse that back out into proper data.

Maybe if you used something like:
`Array
(
[field_1] => strval(5)
[field_2] => strval(banana)
[field_3] => strval(NULL)
)`

It would work?

**Comment by filip24u** [comment]
Passing an empty string as a value is in fact the only way currently expected and supported by FileMaker Data API to delete information from a field. We could certainly make fmRESTor convert null values to empty strings in this case, but we currently hesitate to do that because FileMaker may decide to implement null as a valid input with different behavior from empty string in the future, and then we would have to revert fmRESTor back to NOT do the conversion.
Are there any other people thinking the null to "" conversion would be useful? Please comment, whether you prefer null to be passed to FileMaker Data API as is, or converted to "", and we'll decide for the future depending on the responses.
