### ISSUE TITLE
Passing big parameter in runScript doesn't work

### ISSUE THREAD

**Issue by nexgen** [24u/fmRESTor#7]
When I pass big parameter in runScript (for example, a big json data) via parameter, I get nothing returned.

However, when I pass small parameter like "abc". It does work.

I think it's a problem with parameter being passed via GET method. Is there any way to pass big parameter?

**Comment by beargie** [comment]
@nexgen in case you need to send large amounts of data, i would suggest creating a record in some sort of table in your database with a "payload" of a large script parameter. Then use the Data API to find that payload by a UUID and use it to execute another script with that as a parameter.

Since FileMaker's verb for running scripts is GET, you can't control it to POST data and you need to work within the confines of a standard GET request. (ref: https://fmhelp.filemaker.com/docs/18/en/dataapi/#running-scripts)

**Comment by nexgen** [comment]
Thank you, @beargie I'll try what you suggested.
